---
<%
  kitchen_driver = ENV['KITCHEN_DRIVER'] || 'vagrant'
  puts "-----> driver_plugin: #{kitchen_driver.to_s}"
%>
driver:
  name: <%= kitchen_driver %>
  require_chef_omnibus: 12.8.1
  <% if kitchen_driver == 'ec2' %>
  aws_ssh_key_id:         <%= ENV['AWS_SSH_KEY_ID']         || "test-kitchen" %>
  region:                 <%= ENV['AWS_DEFAULT_REGION']     || "us-west-1" %>
  instance_type: "t2.micro"
  security_group_ids: [<%= ENV['SECURITY_GROUP_IDS'] %>]
  <% end %>
  <% if kitchen_driver == 'vagrant' %>
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 9000, host: 9090}]
  customize:
    memory: 2048
  <% end %>

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  <% if kitchen_driver == 'ec2' %>
  driver_config:
    tags: { "Name": "Test Kitchen" }
  <% end %>

# inspec does not yet use the ssh-agent, so getting this to work via ec2 is problematic
#verifier:
#  name: inspec

suites:
  - name: default
    run_list:
      - recipe[sampleApp::default]
    attributes:
