name 'sampleApp'
maintainer 'FastRobot'
maintainer_email 'cookbooks@fastrobot.com'
license 'Apache 2.0'
description 'Installs/Configures sampleApp'
long_description 'Installs/Configures sampleApp'
version '0.1.1'

depends 'nginx', '~> 2.7.6'
depends 'application_git'
depends 'application_ruby'
depends 'build-essential'
