name 'sampleApp-deploy'
maintainer 'FastRobot'
maintainer_email 'cookbooks@fastrobot.com'
license 'Apache 2.0'
description 'Deploys the sampleApp'
long_description 'Deploys sampleApp to vpc w/ internet gateway, vpc subnet(s), security group, ELB'
version '0.1.0'

depends 'aws', '~> 2.9.3'
depends 'aws-rds', '~> 1.4.1'
