name 'buildcluster'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures buildcluster'
long_description 'Installs/Configures buildcluster'
version '0.1.0'
